[package]
name = "arrows"
version = "0.1.0"
authors = ["lazydancer <jrpucula@gmail.com>"]
edition = "2018"

[dependencies]
piston = "*"
piston2d-graphics = "*"
piston2d-opengl_graphics = "*"
pistoncore-glutin_window = "*"
