[package]
name = "rust_side"
version = "0.1.0"
authors = ["lazydancer <jrpucula@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "rust_side"
crate-type = ["dylib"]